title: Alfred<br/>Wilson-Spencer

logo: /assets/img/SEDI_side_profile.jpg

description: I am a research fellow at the University of Leeds studying the thermochemical evolution of Earthâ€™s core. <br/>
             <br/>
             <a href="mailto:a.j.wilson1@leeds.ac.uk">âœ‰ï¸ a.j.wilson1@leeds.ac.uk</a> <br/>
             <a href="https://scholar.google.co.uk/citations?hl=en&user=POyerY0AAAAJ&view_op=list_works&sortby=pubdate">ğŸ“ Google Scholar </a> <br/>
             <a href="https://fwilson93.github.io/Portfolio/assets/AJWS_CV.pdf">ğŸ“ƒ CV </a>  <br/>
             ğŸ“ Leeds, UK
             
show_downloads: false

google_analytics:

theme: jekyll-theme-minimal
