title: Alfred Wilson-Spencer
logo: /assets/img/headshot.png
description: <a href="https://scholar.google.co.uk/citations?hl=en&user=POyerY0AAAAJ&view_op=list_works&sortby=pubdate">ðŸŽ“ Google Scholar </a> <br/>
             <a href="https://fwilson93.github.io/Portfolio/assets/AJWS_CV.pdf">ðŸ“ƒ CV </a> 
             <a href="mailto:a.j.wilson1@leeds.ac.uk">a.j.wilson1@leeds.ac.uk< /a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
